apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: {{ include "ucreativa-devops-project.fullname" . }}
    tier: backend
spec:
  selector:
    name: backend-deployment
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
