apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: {{ include "ucreativa-devops-project.fullname" . }}
    tier: frontend
spec:
  selector:
    matchLabels:
      app: {{ include "ucreativa-devops-project.fullname" . }}
      name: frontend-deployment
      tier: frontend
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ include "ucreativa-devops-project.fullname" . }}
        name: frontend-deployment
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: '{{ .Values.image.repository }}/frontend:{{ .Values.image.tag}}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
