apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: {{ include "ucreativa-devops-project.fullname" . }}
    tier: frontend
spec:
  selector:
    name: frontend-deployment
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      # nodePort: 30090
