apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: {{ include "ucreativa-devops-project.fullname" . }}
    tier: database
spec:
  selector:
    name: mongo-deployment
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
