apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: {{ include "ucreativa-devops-project.fullname" . }}
    tier: volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /mongo/data
