apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  labels:
    app: {{ include "ucreativa-devops-project.fullname" . }}
data:
  mongo_user: {{ .Values.mongo.username }}
  mongo_password: {{ .Values.mongo.password }}
type: Opaque
